# Generated by Django 4.1.2 on 2022-11-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('categoria', models.TextField(verbose_name='Categoria')),
                ('desarrolladora', models.TextField(verbose_name='Desarrolladora')),
                ('fecha_de_lanzamiento', models.TextField(verbose_name='Lanzamiento')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('imagen', models.ImageField(upload_to='juegos', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'juego',
                'verbose_name_plural': 'juegos',
                'ordering': ['-created'],
            },
        ),
    ]
