# Generated by Django 4.1.2 on 2022-11-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
