# Generated by Django 4.1.2 on 2022-11-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_juegos_id_alter_juegos_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('categoria', models.TextField(verbose_name='Categoria')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('imagen', models.ImageField(upload_to='juegos', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['-created'],
            },
        ),
    ]
