# Generated by Django 4.1.2 on 2022-11-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_carro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
