# Generated by Django 4.1.2 on 2022-11-20 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_delete_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='imagen2',
            field=models.ImageField(default=datetime.date(2022, 11, 20), upload_to='juegos', verbose_name='Imagen2'),
            preserve_default=False,
        ),
    ]
